CREATE DATABASE `webfinance` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

CREATE TABLE `acessos` (
  `ID_ACESSO` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` int(10) unsigned DEFAULT NULL,
  `DT_ACESSO` datetime DEFAULT NULL,
  `IP_ACESSO` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_ACESSO`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `acessos_ibfk_1` FOREIGN KEY (`ID_USUARIO`) REFERENCES `usuarios` (`ID_USUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `contas` (
  `NR_CONTA` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `DS_CONTA` varchar(100) DEFAULT NULL,
  `VL_CONTA` decimal(7,2) DEFAULT NULL,
  `DT_VENCIMENTO` date DEFAULT NULL,
  `DT_INCLUSAO` datetime DEFAULT NULL,
  `DT_ATUALIZACAO` datetime DEFAULT NULL,
  `IE_ATIVO` set('S','N') DEFAULT 'S',
  `IE_DELETADO` set('S','N') DEFAULT 'N',
  `ID_USUARIO` int(10) unsigned DEFAULT NULL,
  `ID_TIPO` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`NR_CONTA`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  KEY `ID_TIPO` (`ID_TIPO`),
  CONSTRAINT `contas_ibfk_1` FOREIGN KEY (`ID_USUARIO`) REFERENCES `usuarios` (`ID_USUARIO`),
  CONSTRAINT `contas_ibfk_2` FOREIGN KEY (`ID_TIPO`) REFERENCES `tipos_conta` (`ID_TIPO`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `registro_transacoes` (
  `NR_TRANSACAO` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NR_CONTA` int(10) unsigned DEFAULT NULL,
  `DT_TRANSACAO` date DEFAULT NULL,
  `ID_USUARIO` int(10) unsigned DEFAULT NULL,
  `VL_TRANSACAO` decimal(7,2) DEFAULT NULL,
  `IE_ATIVO` set('S','N') DEFAULT NULL,
  `IE_DELETADO` set('S','N') DEFAULT NULL,
  PRIMARY KEY (`NR_TRANSACAO`),
  KEY `NR_CONTA` (`NR_CONTA`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `registro_transacoes_ibfk_1` FOREIGN KEY (`NR_CONTA`) REFERENCES `contas` (`NR_CONTA`),
  CONSTRAINT `registro_transacoes_ibfk_2` FOREIGN KEY (`ID_USUARIO`) REFERENCES `usuarios` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `teste` (
  `GuiaPrincipal` varchar(10) DEFAULT NULL,
  `status_conta` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `tipos_conta` (
  `ID_TIPO` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `DS_TIPO` varchar(50) DEFAULT NULL,
  `DT_INCLUSAO` date DEFAULT NULL,
  `ID_USUARIO` int(10) unsigned DEFAULT NULL,
  `IE_CLASSIF_TIPO` set('D','R') DEFAULT NULL,
  `IE_ATIVO` set('S','N') DEFAULT NULL,
  `IE_DELETADO` set('S','N') DEFAULT NULL,
  PRIMARY KEY (`ID_TIPO`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `tipos_conta_ibfk_1` FOREIGN KEY (`ID_USUARIO`) REFERENCES `usuarios` (`ID_USUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `usuarios` (
  `ID_USUARIO` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NM_USUARIO` varchar(100) DEFAULT NULL,
  `LOGIN` varchar(100) NOT NULL,
  `SENHA` varchar(100) NOT NULL,
  `IE_ATIVO` set('S','N') DEFAULT NULL,
  `IE_DELETADO` set('S','N') DEFAULT NULL,
  `DT_INCLUSAO` date DEFAULT NULL,
  `Nome` tinytext DEFAULT NULL,
  `Id` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_USUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

